---
title: "Iteration and List Columns"
author: "Ifrah Fayyaz"
date: "11/11/2021"
output: github_document
---

```{r, message = FALSE, warning = FALSE}
library(tidyverse)

set.seed(1)
```

```{r, message = FALSE, warning = FALSE}
vec_numeric = 5:8
vec_char = c("My", "name", "is", "Ifrah")
vec_logical = c(TRUE, TRUE, TRUE, FALSE)
```

## Lists:

```{r, message = FALSE, warning = FALSE}
l = list(
  vec_numeric = 5:8,
  mat         = matrix(1:8, 2, 4),
  vec_logical = c(TRUE, FALSE),
  summary     = summary(rnorm(1000)))
l

l$vec_numeric

l[[1]]

l[[1]][1:3]
```

## For loops:

```{r, message = FALSE, warning = FALSE}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )

is.list(list_norms)
```

```{r, message = FALSE, warning = FALSE}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}

mean_and_sd(list_norms[[1]])
```

```{r, message = FALSE, warning = FALSE}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```

## Map:

```{r, message = FALSE, warning = FALSE}
output = map(list_norms, mean_and_sd)

output = map(.x = list_norms, ~ mean_and_sd(.x))

output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = median(list_norms[[i]])
}

output = map(list_norms, median)
```

## Map Variants:

```{r, message = FALSE, warning = FALSE}
output = map_dbl(list_norms, median, .id = "input")

output = map_dfr(list_norms, mean_and_sd, .id = "input")

output = map2(.x = input_1, .y = input_2, ~func(arg_1 = .x, arg_2 = .y))

```

## List columns and operations

```{r, message = FALSE, warning = FALSE}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )
```





```{r, message = FALSE, warning = FALSE}

```





```{r, message = FALSE, warning = FALSE}

```





```{r, message = FALSE, warning = FALSE}

```




```{r, message = FALSE, warning = FALSE}

```





```{r, message = FALSE, warning = FALSE}

```





```{r, message = FALSE, warning = FALSE}

```
