---
title: "Writing Functions"
author: "Ifrah Fayyaz"
date: "11/4/2021"
output: html_document
---

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(rvest)
```

## z-scores

```{r, message = FALSE, warning = FALSE}
x_vec = rnorm(25, mean = 5, sd = 4)

(x_vec - mean(x_vec)) / sd(x_vec)

z_scores = function(x) {
  z = (x - mean(x)) / sd(x)
  return(z)
}

z_scores(x = x_vec)

y_vec = rnorm(40, mean = 12, sd = 0.3)

z_scores(y_vec)
```



```{r, message = FALSE, warning = FALSE}

mean_and_sd = function(x) {
  if (!is.numeric(x)) {
    stop("x needs to be numeric")
  }
  if (length(x) < 3) {
    stop("x should have at least 3 numbers")
  }
  mean_x = mean(x)
  sd_x = sd(x)
  
  output_df = 
    tibble(
      mean = mean_x,
      sd = sd_x
    )
  return(output_df)
}

mean_and_sd(x_vec)
mean_and_sd(y_vec)

```

## Different sample sizes, mean and sd

```{r, message = FALSE, warning = FALSE}
sim_data =
  tibble(
    x = rnorm(30, mean = 2, sd = 3)
  )

sim_data %>%
  summarize(
    mean = mean(x),
    sd = sd(x)
  )

```

## Lets write a function that simulates data, computes the mean and sd

```{r, message = FALSE, warning = FALSE}
sim_mean_sd = function(n, mu, sigma) {
  # do checks on inputs
  
      sim_data =
      tibble(
        x = rnorm(n = n, mean = mu, sd = sigma)
      )
    
    sim_data %>%
      summarize(
        mean = mean(x),
        sd = sd(x)
      )
}

sim_mean_sd(30, 5, 2)

```



```{r, message = FALSE, warning = FALSE}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"


get_page_reviews = function(pageurl) {
    page_html = read_html(pageurl)
    review_titles = 
      page_html %>%
      html_nodes(".a-text-bold span") %>%
      html_text()
    
    review_stars = 
      page_html %>%
      html_nodes("#cm_cr-review_list .review-rating") %>%
      html_text() %>%
      str_extract("^\\d") %>%
      as.numeric()
    
    review_text = 
      page_html %>%
      html_nodes(".review-text-content span") %>%
      html_text() %>% 
      str_replace_all("\n", "") %>% 
      str_trim()
    
    reviews = 
      tibble(
        title = review_titles,
        stars = review_stars,
        text = review_text
      )
  return(reviews)
}

base_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

urls = str_c(base_url, 1:5)

bind_rows(
  get_page_reviews(urls[1]),
  get_page_reviews(urls[2]),
  get_page_reviews(urls[3]),
  get_page_reviews(urls[4]),
  get_page_reviews(urls[5])
)
```

```{r, message = FALSE, warning = FALSE}

```

```{r, message = FALSE, warning = FALSE}

```

```{r, message = FALSE, warning = FALSE}

```

```{r, message = FALSE, warning = FALSE}

```

```{r, message = FALSE, warning = FALSE}

```

```{r, message = FALSE, warning = FALSE}

```

```{r, message = FALSE, warning = FALSE}

```

```{r, message = FALSE, warning = FALSE}

```
